### ISSUE TITLE
$dxLevel is NaN in deeper levels

### ISSUE THREAD

**Issue by Madd0g** [dotJEM/angular-tree#10]
Seems like the latest rewrite broke that.

**Comment by Madd0g** [comment]
I played around and it seems impossible now? Can someone at least chime in with an opinion on whether it's possible with the way it's currently built?

If I understand correctly from the commit where it [supposedly broke](https://github.com/dotJEM/angular-tree/commit/e1815e835d11cf7f954d5610ebaa18e7cca08eaa) - the `$NodeDirectiveLink` is now transcluded and cannot know the depth because all that is handled by `ng-repeat`?

**Comment by jeme** [comment]
How deep are we talking?...

http://plnkr.co/edit/ZHOElHgmf6c0hok9fgXj?p=preview

I tried expanding the example above beyond 250 and it seemed to work just fine.
At that level of nesting things can quickly get very ugly... I had to limit child nodes to 1 in order to get that for otherwise memory usage would obviously rise exponentially which quickly lead to crashes...

Do you by any chance bind anything that would maybe "change" the $dxLevel value at some point, because that would ofc. break the levels below that.

**Comment by Madd0g** [comment]
I have my own directive, which I pass the `$dxLevel` to.

Something like this:
`ul dx-start-with='someObj'`

`li custom-component depth="$dxLevel" ng-repeat="item in coll" item="item"`

The reason I thought it broke, because in the debugger I actually see `$dxLevel: NaN` if I go up the scopes from my component.

I'll try to reproduce my problem in that fiddle.

**Comment by Madd0g** [comment]
http://plnkr.co/edit/junRc4FxV2IKGXbSbGGa?p=preview

So this shows the problem, sorry I broke the demo a little bit but the problem is visible.

Should something like this work?

**Comment by jeme** [comment]
Arh... No that won't work out of the box.

What you are doing is that your creating a isolate scope where in your actually trying to to the connect. Because it is a isolate scope, it breaks the prototypical inheritance.

As a workaround you might be able to push depth back to $dxLevel, but I think I would generally advice against bridging the dx-start-with to a dx-connect over an isolate scope as it will cause you to jump in and out of isolate scopes which will most likely strike some general angular quirks...

So I would keep the dx-start-with and dx-connect in the same scope tree at all times, if you must have this within the directive, and can't restructure it in another way, transclude could be a possibility.

Like so:; http://plnkr.co/edit/JeiydRtFvrI7cDoV5vuT?p=preview

But I think overall it would be better to restructure recursive nodes out of the directive and then let the directive only concern be to render the nodes value and not it's children. As the more we transclude things the more we take performance hits... This is ofc. always subject to "is it fast enough, then it's good enough".

**Comment by Madd0g** [comment]
Huh, the method with transclude solves my problem and it even makes sense to have the repeater defined where the loop is defined. 

Thanks a lot! Very happy to see this solved.
